/**
 * \file doc_test.H
 * \brief A file to test doxygen capabilites.
 *
 * A demonstration of all the fun that can be had when we document
 * with Dxoygen.
 *
 */



/**
 * \fn void day_of_the_week(int day, int month, int year)
 * \brief Determines the day of the week as MTWThF.
 *
 * \param day  The day.
 * \param month The month from 0 to 11.
 * \param year The year using the *Ancient Macedonian* calendar.
 *
 * Determines the day of the week using an advanced formula
 * that usually works if its not during daylight savings. This
 * function is only for demonstration purposes.
 *
 */

 void day_of_the_week(int day, int month, int year){
 }
