name: Build and Deploy Docs
on: [push, pull_request]

concurrency:
  group: ${{ github.ref }}-${{ github.head_ref }}-docs
  cancel-in-progress: true

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v7
        with:
          persist-credentials: false

      - name: Dependencies
        run: |
          .github/workflows/dependencies/documentation.sh
          echo "Installing python packages for docs..."

          python3 -m pip install --upgrade pip
          python3 -m pip install sphinx==5.0.0 sphinx_rtd_theme sphinxcontrib.bibtex docutils sphinx-toolbox

      - name: Build Doxygen Docs
        run: |
          ./build_doxygen_docs.sh

      - name: Install and Build
        run: |
          cd Docs
          echo "Build the Sphinx documentation for AMReX-Hydro."
          ## build latex pdf -- disabled due to conflict with predefined math expressions in rst files
          #make latexpdf
          #mv build/latex/amrex-hydro.pdf source/
          make html

      - name: Deploy
        if: github.event_name == 'push' && github.repository == 'AMReX-Fluids/AMReX-Hydro' && github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          access-token: ${{ secrets.DEPLOY_DOCS_HYDRO }}
          repository-name: AMReX-Fluids/AMReX-Fluids.github.io
          branch: main # The branch the action should deploy to.
          folder: Docs/build/html # The folder the action should deploy.
          target-folder: amrex-hydro/docs_html # The folder the action should deploy to.
          clean: false # Do not remove existing files from the deploy target.

      - name: Deploy Doxygen
        if: github.event_name == 'push' && github.repository == 'AMReX-Fluids/AMReX-Hydro' && github.ref == 'refs/heads/development'
        uses: JamesIves/github-pages-deploy-action@v4.8.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          access-token: ${{ secrets.DEPLOY_DOCS_HYDRO }}
          repository-name: AMReX-Fluids/AMReX-Fluids.github.io
          branch: main # The branch the action should deploy to.
          folder: Docs/Doxygen/html # The folder the action should deploy.
          target-folder: amrex-hydro/Doxygen/html # The folder the action should deploy to.
          clean: false # Do not remove existing files from the deploy target.

